# Generated by Django 3.1.7 on 2021-04-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNumber', models.AutoField(primary_key=True, serialize=False)),
                ('accountType', models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking')], default='Savings', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isActive', models.CharField(default='Y', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
