# Generated by Django 3.1.7 on 2021-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210507_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
