# Generated by Django 3.1.7 on 2021-05-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_admin'),
        ('users', '0003_auto_20210417_1846'),
    ]

    operations = [
    ]
