# Generated by Django 3.1.7 on 2021-04-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(auto_created=True)),
                ('payeeName', models.CharField(max_length=255)),
                ('payeeAccount', models.PositiveBigIntegerField()),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly'), ('Once', 'Once')], default='Once', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nextDueDate', models.DateField(null=True)),
                ('lastPaymentDate', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
